build: replace travis with github ci
btcsuite/btcutil pull request #167
Opened 2020-05-13 13:37 UTC by dajohi

2020-05-13 13:38 UTC, dajohi commented
https://github.com/dajohi/btcutil/runs/670938539

2020-05-18 07:22 UTC, onyb commented on goclean.sh
> -# goveralls -coverprofile=profile.cov -service=travis-ci
Just to be sure, are we still performing code-coverage checks?

2020-07-06 18:36 UTC, onyb commented on goclean.sh
> +  #env GORACE=halt_on_error=1 go test -race ${module}/...
I think you forgot to run the tests here.

2020-08-29 09:09 UTC, onyb commented
@dajohi Any update on this? If you would prefer, I can take this over for the last fixes.

2020-08-30 21:39 UTC, dajohi commented
@onyb updated

2020-08-30 22:02 UTC, onyb requested changes
Last two remarks:
* Test coverage is missing.
* Maybe it makes sense  to bump the Go version in `go.mod` to **1.15** since you updated the version on GitHub Action.

2020-08-30 22:02 UTC, onyb commented on goclean.sh
> +  (cd $MODNAME && env GORACE=halt_on_error=1 go test -race)
This is missing the test coverage part. You just need to collect the coverage report for each module and add the following to the GitHub action YAML  file:

```
      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
```

2020-09-07 11:03 UTC, onyb commented
@dajohi Recent changes look good to me, but the [build](https://github.com/dajohi/btcutil/runs/1051935634) on your fork appears to be failing.

2020-10-16 21:33 UTC, Roasbeef commented
Needs a rebase.

2020-10-21 21:56 UTC, dajohi commented
@onyb @Roasbeef ready for review..

2020-10-22 10:09 UTC, onyb requested changes

2020-10-22 10:09 UTC, onyb commented on goclean.sh
> +    env GORACE=halt_on_error=1 go test -race -covermode=atomic -coverprofile=profile.tmp && \
I think it is necessary to add `./...` here:
```suggestion
    env GORACE=halt_on_error=1 go test -race -covermode=atomic -coverprofile=profile.tmp ./... && \
```

You can verify it by doing:

```
$ cd btcutil
$ go test -v | wc -l
53
$  go test -v ./... | wc -l
179
```

2020-10-23 16:26 UTC, onyb approved these changes
Finally! 🚀

2020-10-26 13:48 UTC, jcvernaleo approved these changes
OK

2020-10-26 13:49 UTC, merged