Drop string construction from integers
btcsuite/btcutil pull request #184
Opened 2020-09-14 12:55 UTC by pascaldekloe

Go no longer allows it. The FIX is a good demonstration on the why. ;-)

2020-10-12 08:53 UTC, onyb approved these changes

2020-10-12 13:58 UTC, jcvernaleo requested changes
Looks good.  Could you just squash to one commit and then I can merge.

If you can't squash for any reason just let me know and I can handle it on my end.

Thanks!

2020-10-15 02:47 UTC, pascaldekloe commented
🛎️

2020-10-15 13:23 UTC, jcvernaleo approved these changes
OK

2020-10-15 13:23 UTC, jcvernaleo commented
Looks all good now.  Thanks!

2020-10-15 13:23 UTC, merged